global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'shardkv'
    static_configs:
      - targets:
          - '127.0.0.1:8100'
          - '127.0.0.1:8110'
          - '127.0.0.1:8120'
          - '127.0.0.1:8130'
          - '127.0.0.1:8140'
          - '127.0.0.1:8150'
          - '127.0.0.1:8160'
          - '127.0.0.1:8170'
          - '127.0.0.1:8180'
